---
suites:
  - name: default
    run_list:
      - recipe[mapr_installation::default]
      - recipe[mapr-spark::default]
    attributes:
      java:
        version: 'java-1.8.0-openjdk-devel'
        home: '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-1.b16.el6_7.x86_64/'
      mapr:
        cldb: ['node-1']
        zk: ['node-1']
        rm: ['node-1']
        hs: 'node-1'

driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids: <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  instance_type: <%= ENV['INSTANCE_SIZE'] %>
  associate_public_ip: false
  interface: private
  user_data: <%= ENV['USER_DATA_PATH'] %>

provisioner:
  name: chef_zero

transport:
  username: cloud-user
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: <%= ENV['AWS_PLATFORM_NAME'] %>

driver:
  image_id: <%= ENV['AWS_AMI_ID'] %>

