driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  instance_type: <%= ENV['INSTANCE_SIZE'] %>
  associate_public_ip: false
  interface: private
  user_data: <%= ENV['USER_DATA_PATH'] %>
  block_device_mappings:
    - ebs_device_name: /dev/sdb
      ebs_volume_size: 10
      ebs_delete_on_termination: true

provisioner:
  name: chef_zero

transport:
  username: cloud-user
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: <%= ENV['AWS_PLATFORM_NAME'] %>
    driver:
      image_id: <%= ENV['AWS_AMI_ID'] %>


suites:
  - name: default
    run_list:
      - role[mapr-node]
    attributes:
      mapr:
        cldb: '*'
        zk: '*'
        rm: '*'
        hs: '*'
      ssh_keys:
        mapr: ['mapr']

